---
title: "analysis of processed FCM data from SP10 entrapment assay"
output: html_notebook
---

```{r}
# clear environment
rm(list = ls())
library(tidyverse)
```

I first need to collect all the data from the cluster pipeline.
* currently only delta6 on DSM is really well clustered
* delta6 on LB is OK in x100
* W23 data is incorrect

I will first collect it all and then fikter out the good data.
```{r, include=FALSE}
# get all the file names to collect
files <- list.files("../data/entrap_data/output/", recursive = TRUE, full.names = TRUE)
d <- data.frame()

for (f in files){
      #get the day from file name
      day <- parse_number(gsub(".*day","",f))
      tmp <- read_csv(f)
      tmp$day <- day
      d <- rbind(d, tmp)
}
rm (tmp)

```


```{r}
filter(d, host=="delta6")%>%
      filter(media=="DSM")%>%
      ggplot(aes(x=phage, y=spore.ml))+
            geom_point(aes(shape=rep, color=time))+
            facet_grid(day~dilution)
            
```

```{r}
filter(d, host=="delta6")%>%
      filter(media=="DSM")%>%
      # filter(veg>1000)%>%
      ggplot(aes(x=phage, y=veg.ml))+
            geom_jitter(aes(shape=rep, color=time), width=.2, height = 0)+
            scale_y_log10()+
            facet_grid(day~dilution)
            
```

```{r}
filter(d, host=="delta6")%>%
      filter(media=="LB")%>%
      filter(dilution=="x100")%>%
      ggplot(aes(x=phage, y=spore.ml))+
            geom_jitter(aes(shape=rep, color=time), width=.2, height = 0)+
            scale_y_log10()+
            facet_grid(day~dilution)

filter(d, host=="delta6")%>%
      filter(media=="LB")%>%
      filter(dilution=="x100")%>%
      ggplot(aes(x=phage, y=veg.ml))+
            geom_jitter(aes(shape=rep, color=time), width=.2, height = 0)+
            scale_y_log10()+
            facet_grid(day~dilution)
            
```

```{r}
filter(d, host=="delta6")%>%
      filter(media=="DSM")%>%
   gather(key="pop", value = "cell.ml", c("veg.ml", "spore.ml"))%>%
      # filter(veg>1000)%>%
      ggplot(aes(x=interaction(phage,time,rep), y=cell.ml))+
            geom_bar(aes(fill=pop), stat = "identity")+
            scale_y_log10()+
            facet_grid(day~dilution)
            
```